apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stolosio
  namespace: stolosio
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: stolosio-chart
  values:
    database:
      existingSecret: stolosio-connections
      urlSecretKey: database-url
    nats:
      existingSecret: stolosio-connections
      urlSecretKey: nats-url
      seedSecretKey: nats-seed
    imagePullSecrets:
      - name: ghcr-auth
