apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: stolosio-chart
  namespace: stolosio
spec:
  interval: 10m
  url: oci://ghcr.io/elei-io/charts/stolosio
  ref:
    semver: ">=0.1.12 <0.2.0"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  secretRef:
    name: ghcr-auth
