"""SQLAlchemy persistence models."""

from backend.db.models.gateway import (
    AcquisitionAttempt,
    ExternalProviderLimit,
    ExternalProviderLimitEvent,
    FleetConfigurationEvent,
    GatewaySession,
    GatewayState,
    NetworkPolicyConfiguration,
    ProviderFleet,
    ProviderInstance,
    ProviderState,
    SessionEventRecord,
)
from backend.db.models.observability import (
    Domain,
    DomainProviderCostStat,
    DomainProviderHealth,
    DomainProviderTransitionStat,
    DomainRoutingPreference,
    HealthProbe,
    ProviderCommandCostStat,
    ProviderRoutingProfile,
    RoutingConfiguration,
    SessionDomain,
)

__all__ = [
    "AcquisitionAttempt",
    "ExternalProviderLimit",
    "ExternalProviderLimitEvent",
    "Domain",
    "DomainProviderCostStat",
    "DomainProviderHealth",
    "DomainRoutingPreference",
    "DomainProviderTransitionStat",
    "FleetConfigurationEvent",
    "GatewaySession",
    "GatewayState",
    "NetworkPolicyConfiguration",
    "ProviderState",
    "ProviderFleet",
    "ProviderInstance",
    "ProviderCommandCostStat",
    "ProviderRoutingProfile",
    "HealthProbe",
    "RoutingConfiguration",
    "SessionDomain",
    "SessionEventRecord",
]
