FROM ubuntu:24.10@sha256:cdf755952ed117f6126ff4e65810bf93767d4c38f5c7185b50ec1f1078b464cc
RUN apt-get update && apt-get install -y --no-install-recommends \
    squid nftables iproute2 python3 util-linux ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY egress.py fetch-proxy-entrypoint.sh /opt/stolosio/
COPY squid.conf /etc/squid/squid.conf
EXPOSE 3128
ENTRYPOINT ["/bin/sh", "/opt/stolosio/fetch-proxy-entrypoint.sh"]
