http_port 3128
visible_hostname stolosio-fetch-proxy
pid_filename none
cache_log /tmp/squid-cache.log
access_log none
cache_store_log none
cache deny all
cache_mem 16 MB
pinger_enable off
forwarded_for delete
via off
acl manager proto cache_object
acl CONNECT method CONNECT
acl web_ports port 80 443
acl tls_ports port 443
acl blocked_dst dst "/etc/squid/blocked-destinations.txt"
http_access deny manager
http_access deny !web_ports
http_access deny CONNECT !tls_ports
http_access deny blocked_dst
http_access allow all
shutdown_lifetime 1 seconds
