"""initial schema

Revision ID: 20260718_01
Revises:
Create Date: 2026-07-18 12:05:38.921366
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260718_01"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_count", sa.BigInteger(), nullable=False),
        sa.Column(
            "eligible_acquisition_count", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hostname"),
    )
    op.create_index(op.f("ix_domains_last_seen_at"), "domains", ["last_seen_at"], unique=False)
    op.create_table(
        "external_provider_limits",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("max_active_sessions", sa.Integer(), nullable=False),
        sa.Column("max_queued_attempts", sa.Integer(), nullable=False),
        sa.Column("configuration_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("max_active_sessions >= 0", name="ck_external_limit_active_nonnegative"),
        sa.CheckConstraint("max_queued_attempts >= 0", name="ck_external_limit_queue_nonnegative"),
        sa.PrimaryKeyConstraint("provider"),
    )
    op.create_table(
        "gateway_provider_state",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("provider"),
    )
    op.create_table(
        "gateway_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=False),
        sa.Column("client_reference", sa.String(length=36), nullable=True),
        sa.Column("requested_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_reason", sa.String(length=64), nullable=True),
        sa.Column("health_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gateway_sessions_health_evaluated_at"),
        "gateway_sessions",
        ["health_evaluated_at"],
        unique=False,
    )
    op.create_index(
        "ix_gateway_sessions_lease", "gateway_sessions", ["lease_expires_at"], unique=False
    )
    op.create_index("ix_gateway_sessions_state", "gateway_sessions", ["state"], unique=False)
    op.create_index(
        "ux_gateway_sessions_client_reference",
        "gateway_sessions",
        ["client_reference"],
        unique=True,
    )
    op.create_table(
        "gateway_state",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "provider_fleets",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("minimum_instances", sa.Integer(), nullable=False),
        sa.Column("maximum_instances", sa.Integer(), nullable=False),
        sa.Column("session_capacity_per_instance", sa.Integer(), nullable=False),
        sa.Column("scale_down_cooldown_seconds", sa.Integer(), nullable=False),
        sa.Column("max_queued_attempts", sa.Integer(), nullable=False),
        sa.Column("desired_instances", sa.Integer(), nullable=False),
        sa.Column("configuration_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_scale_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_scale_down_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idle_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("controller_status", sa.String(length=64), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "maximum_instances >= minimum_instances", name="ck_fleet_maximum_gte_minimum"
        ),
        sa.CheckConstraint("minimum_instances >= 0", name="ck_fleet_minimum_nonnegative"),
        sa.CheckConstraint("max_queued_attempts >= 0", name="ck_fleet_queue_nonnegative"),
        sa.CheckConstraint("scale_down_cooldown_seconds > 0", name="ck_fleet_cooldown_positive"),
        sa.CheckConstraint("session_capacity_per_instance >= 1", name="ck_fleet_capacity_positive"),
        sa.PrimaryKeyConstraint("provider"),
    )
    op.create_table(
        "provider_routing_profiles",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("automatic_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("cost_units_per_second", sa.BigInteger(), nullable=False),
        sa.Column("provider_contract_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("cost_units_per_second >= 0", name="ck_provider_cost_nonnegative"),
        sa.PrimaryKeyConstraint("provider"),
    )
    op.create_table(
        "routing_configuration",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("default_provider", sa.String(length=32), nullable=False),
        sa.Column(
            "existing_domain_probe_rate_basis_points",
            sa.Integer(),
            server_default="100",
            nullable=False,
        ),
        sa.Column(
            "required_health_confirmations", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column("health_policy_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("configuration_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "existing_domain_probe_rate_basis_points BETWEEN 0 AND 10000",
            name="ck_routing_probe_rate",
        ),
        sa.CheckConstraint(
            "required_health_confirmations >= 1", name="ck_routing_required_health_confirmations"
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "provider_command_cost_stats",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("method", sa.String(length=128), nullable=False),
        sa.Column("command_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("failed_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("interrupted_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("total_duration_ms", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "total_provider_latency_ms",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "total_harbor_queue_ms",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "attributed_browser_time_ms",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "attributed_cost_units",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("provider", "method"),
    )
    op.create_table(
        "domain_provider_cost_stats",
        sa.Column("domain_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("observed_attempt_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("total_cost_units", sa.BigInteger(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("domain_id", "provider"),
    )
    op.create_table(
        "domain_provider_health",
        sa.Column("domain_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("health_state", sa.String(length=16), nullable=False),
        sa.Column("successful_probe_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("failed_probe_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("inconclusive_probe_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "navigation_state", sa.String(length=16), server_default="unknown", nullable=False
        ),
        sa.Column("status_state", sa.String(length=16), server_default="unknown", nullable=False),
        sa.Column("headers_state", sa.String(length=16), server_default="unknown", nullable=False),
        sa.Column("content_state", sa.String(length=16), server_default="unknown", nullable=False),
        sa.Column("failure_reason_code", sa.String(length=64), nullable=True),
        sa.Column("last_status_code", sa.Integer(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_healthy_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_policy_version", sa.Integer(), nullable=False),
        sa.Column("provider_contract_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "health_state IN ('unknown', 'healthy', 'unhealthy', 'inconclusive')",
            name="ck_domain_provider_health_state",
        ),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("domain_id", "provider"),
    )
    op.create_table(
        "domain_provider_transition_stats",
        sa.Column("domain_id", sa.BigInteger(), nullable=False),
        sa.Column("from_provider", sa.String(length=32), nullable=False),
        sa.Column("to_provider", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("transition_count", sa.BigInteger(), nullable=False),
        sa.Column("last_trigger_method", sa.String(length=128), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("domain_id", "from_provider", "to_provider", "trigger"),
    )
    op.create_table(
        "external_provider_limit_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("configuration_version", sa.Integer(), nullable=False),
        sa.Column("previous_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider"], ["external_provider_limits.provider"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_provider_limit_events_provider"),
        "external_provider_limit_events",
        ["provider"],
        unique=False,
    )
    op.create_table(
        "fleet_configuration_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("configuration_version", sa.Integer(), nullable=False),
        sa.Column("previous_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["provider"], ["provider_fleets.provider"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fleet_configuration_events_provider",
        "fleet_configuration_events",
        ["provider", "id"],
        unique=False,
    )
    op.create_table(
        "health_probes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("domain_id", sa.BigInteger(), nullable=False),
        sa.Column("source_session_id", sa.String(length=36), nullable=False),
        sa.Column("cohort_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_provider", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("sampling_bucket", sa.Integer(), nullable=True),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=True),
        sa.Column("navigation_state", sa.String(length=16), nullable=True),
        sa.Column("status_state", sa.String(length=16), nullable=True),
        sa.Column("headers_state", sa.String(length=16), nullable=True),
        sa.Column("content_state", sa.String(length=16), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column(
            "reason_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "content_facts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "comparison_state", sa.String(length=32), server_default="pending", nullable=False
        ),
        sa.Column("cost_units", sa.BigInteger(), nullable=True),
        sa.Column("lease_owner", sa.String(length=36), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "comparison_state IN ('pending', 'not_applicable', 'inconclusive', "
            "'comparable', 'materially_incomplete')",
            name="ck_health_probe_comparison_state",
        ),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'completed', 'failed')", name="ck_health_probe_state"
        ),
        sa.CheckConstraint(
            "trigger IN ('new_domain', 'existing_sample', 'manual')", name="ck_health_probe_trigger"
        ),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_session_id"], ["gateway_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_health_probes_cohort", "health_probes", ["cohort_id", "state"], unique=False
    )
    op.create_index(
        "ix_health_probes_queue", "health_probes", ["state", "created_at"], unique=False
    )
    op.create_index(
        "ux_health_probes_automatic_source",
        "health_probes",
        ["source_session_id", "candidate_provider"],
        unique=True,
        postgresql_where=sa.text("trigger IN ('new_domain', 'existing_sample')"),
    )
    op.create_index(
        "ux_health_probes_initial",
        "health_probes",
        ["domain_id", "candidate_provider"],
        unique=True,
        postgresql_where=sa.text("trigger = 'new_domain'"),
    )
    op.create_table(
        "provider_instances",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("endpoint", sa.String(length=512), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observation_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("draining_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("capacity >= 1", name="ck_provider_instance_capacity_positive"),
        sa.ForeignKeyConstraint(["provider"], ["provider_fleets.provider"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_provider_instances_observation_expiry",
        "provider_instances",
        ["observation_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_provider_instances_provider_state",
        "provider_instances",
        ["provider", "state"],
        unique=False,
    )
    op.create_table(
        "session_domains",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("domain_id", sa.BigInteger(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["gateway_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id", "domain_id"),
    )
    op.create_table(
        "session_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["gateway_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_session_events_attempt_id"), "session_events", ["attempt_id"], unique=False
    )
    op.create_index("ix_session_events_occurred", "session_events", ["occurred_at"], unique=False)
    op.create_index(
        op.f("ix_session_events_published_at"), "session_events", ["published_at"], unique=False
    )
    op.create_index(
        "ix_session_events_session", "session_events", ["session_id", "id"], unique=False
    )
    op.execute(sa.schema.CreateSequence(sa.Sequence("harbor_attempt_queue_sequence")))
    op.create_table(
        "acquisition_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_instance_id", sa.String(length=128), nullable=True),
        sa.Column("provider_session_id", sa.String(length=128), nullable=True),
        sa.Column("resolved_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("setting_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "queue_sequence",
            sa.BigInteger(),
            server_default=sa.text("nextval('harbor_attempt_queue_sequence')"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acquiring_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capacity_occupied_ms", sa.BigInteger(), nullable=True),
        sa.Column("browser_connected_ms", sa.BigInteger(), nullable=True),
        sa.Column("provider_reported_ms", sa.BigInteger(), nullable=True),
        sa.Column("estimated_billable_ms", sa.BigInteger(), nullable=True),
        sa.Column("chargeable_time_ms", sa.BigInteger(), nullable=True),
        sa.Column("cost_basis", sa.String(length=32), nullable=True),
        sa.Column("cost_rate_units_per_second", sa.BigInteger(), nullable=True),
        sa.Column("terminal_reason", sa.String(length=64), nullable=True),
        sa.Column("domain_id", sa.BigInteger(), nullable=True),
        sa.Column("selection_reason", sa.String(length=32), nullable=True),
        sa.Column("plan_version", sa.Integer(), nullable=True),
        sa.Column("plan_position", sa.Integer(), nullable=True),
        sa.Column("transition_trigger", sa.String(length=64), nullable=True),
        sa.Column("estimated_cost_units", sa.BigInteger(), nullable=True),
        sa.Column("modeled_cost_units", sa.BigInteger(), nullable=True),
        sa.Column(
            "command_summary",
            postgresql.JSONB(astext_type=sa.Text(), none_as_null=True),
            nullable=True,
        ),
        sa.Column(
            "command_cost_projected",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("cost_projected", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["provider_instance_id"], ["provider_instances.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["gateway_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ordinal"),
    )
    op.create_index(
        op.f("ix_acquisition_attempts_domain_id"),
        "acquisition_attempts",
        ["domain_id"],
        unique=False,
    )
    op.create_index(
        "ix_acquisition_attempts_finished_provider",
        "acquisition_attempts",
        ["finished_at", "provider"],
        unique=False,
    )
    op.create_index(
        "ix_acquisition_attempts_instance_state",
        "acquisition_attempts",
        ["provider_instance_id", "state"],
        unique=False,
    )
    op.create_index(
        "ix_acquisition_attempts_provider_state",
        "acquisition_attempts",
        ["provider", "state"],
        unique=False,
    )
    op.create_index(
        "ix_acquisition_attempts_queue",
        "acquisition_attempts",
        ["provider", "state", "queue_sequence"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_acquisition_attempts_queue", table_name="acquisition_attempts")
    op.drop_index("ix_acquisition_attempts_provider_state", table_name="acquisition_attempts")
    op.drop_index("ix_acquisition_attempts_finished_provider", table_name="acquisition_attempts")
    op.drop_index("ix_acquisition_attempts_instance_state", table_name="acquisition_attempts")
    op.drop_index(op.f("ix_acquisition_attempts_domain_id"), table_name="acquisition_attempts")
    op.drop_table("acquisition_attempts")
    op.execute(sa.schema.DropSequence(sa.Sequence("harbor_attempt_queue_sequence")))
    op.drop_index("ix_session_events_session", table_name="session_events")
    op.drop_index(op.f("ix_session_events_published_at"), table_name="session_events")
    op.drop_index("ix_session_events_occurred", table_name="session_events")
    op.drop_index(op.f("ix_session_events_attempt_id"), table_name="session_events")
    op.drop_table("session_events")
    op.drop_table("session_domains")
    op.drop_index("ix_provider_instances_provider_state", table_name="provider_instances")
    op.drop_index("ix_provider_instances_observation_expiry", table_name="provider_instances")
    op.drop_table("provider_instances")
    op.drop_index(
        "ux_health_probes_initial",
        table_name="health_probes",
        postgresql_where=sa.text("trigger = 'new_domain'"),
    )
    op.drop_index(
        "ux_health_probes_automatic_source",
        table_name="health_probes",
        postgresql_where=sa.text("trigger IN ('new_domain', 'existing_sample')"),
    )
    op.drop_index("ix_health_probes_queue", table_name="health_probes")
    op.drop_index("ix_health_probes_cohort", table_name="health_probes")
    op.drop_table("health_probes")
    op.drop_index("ix_fleet_configuration_events_provider", table_name="fleet_configuration_events")
    op.drop_table("fleet_configuration_events")
    op.drop_index(
        op.f("ix_external_provider_limit_events_provider"),
        table_name="external_provider_limit_events",
    )
    op.drop_table("external_provider_limit_events")
    op.drop_table("domain_provider_transition_stats")
    op.drop_table("domain_provider_health")
    op.drop_table("domain_provider_cost_stats")
    op.drop_table("provider_command_cost_stats")
    op.drop_table("routing_configuration")
    op.drop_table("provider_routing_profiles")
    op.drop_table("provider_fleets")
    op.drop_table("gateway_state")
    op.drop_index("ux_gateway_sessions_client_reference", table_name="gateway_sessions")
    op.drop_index("ix_gateway_sessions_state", table_name="gateway_sessions")
    op.drop_index("ix_gateway_sessions_lease", table_name="gateway_sessions")
    op.drop_index(op.f("ix_gateway_sessions_health_evaluated_at"), table_name="gateway_sessions")
    op.drop_table("gateway_sessions")
    op.drop_table("gateway_provider_state")
    op.drop_table("external_provider_limits")
    op.drop_index(op.f("ix_domains_last_seen_at"), table_name="domains")
    op.drop_table("domains")
    # ### end Alembic commands ###
