"""Generate shared capture enums: uv run python -m scripts.export_admin_contracts [--check]."""

import argparse
import json
from pathlib import Path
from typing import get_args, get_type_hints

from pagecapture.api import Attempt, DecisionCode, Tier

from backend.proxy.workload_facts import CapturePath

DESTINATION = Path(__file__).resolve().parents[1] / "admin/src/types/contracts.ts"


def render() -> str:
    contracts = {
        "CapturePath": CapturePath,
        "CaptureTier": Tier,
        "CaptureDecisionCode": DecisionCode,
        "CaptureDecision": get_type_hints(Attempt)["decision"],
    }
    lines = ["// Generated by scripts/export_admin_contracts.py. Do not edit by hand.", ""]
    for name, contract in contracts.items():
        lines.append(f"export type {name} =")
        lines.extend(f"  | {json.dumps(value)}" for value in get_args(contract))
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    source = render()
    if arguments.check:
        if DESTINATION.read_text() != source:
            parser.exit(
                1,
                "Admin contracts are stale; run uv run python -m scripts.export_admin_contracts\n",
            )
    else:
        DESTINATION.write_text(source)


if __name__ == "__main__":
    main()
