apiVersion: v2
name: stolosio
description: CDP-compatible browser acquisition gateway
type: application
version: 0.1.16
appVersion: "0.1.15"
home: https://github.com/elei-io/stolosio
sources:
  - https://github.com/elei-io/stolosio
annotations:
  org.opencontainers.image.source: https://github.com/elei-io/stolosio
