// Generated by scripts/export_admin_contracts.py. Do not edit by hand.

export type CapturePath =
  | "http"
  | "managed"
  | "local_resolution"
  | "challenge_resolution"

export type CaptureTier =
  | "direct"
  | "managed"
  | "local_resolution"
  | "challenge_resolution"

export type CaptureDecisionCode =
  | "cache_url"
  | "cache_pattern"
  | "canary"
  | "verify_http"
  | "assessment"
  | "content_comparison"
  | "acquisition"
  | "media_type"

export type CaptureDecision =
  | "accept"
  | "escalate"
  | "fail"
